#!/bin/bash
# Author:       Kinker Wen <hijack111@gmail.com>
# Description:  Automatically change configuration of Mac OS X based on location

# Example of airport output:

#           .....: .........
#            SSID: Kinker Wen’s iPhone
#             MCS: 7
#         channel: 1

# Example of scselect output:

# Defined sets include: (* == current set)
#  C .........UUID.......................	(...SSID.......)
#    FD131CDC-1997-4B72-A3CD-9480E035962D	(TP-LINK_4B9384)
#  * 238D477A-0F62-4D66-9790-16D2D1553364	(Kinker Wen’s iPhone)
#    3062DE7E-861F-4B85-BA4E-646EE414AD63	(NETGEAR)

# Get the connected WiFi SSID
SSID=$(/System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport -I | \
       sed -ne 's/^ *SSID: \(.*\)$/\1/p')

# MATCH_LOC_UUID == '   UUID (SSID)'
MATCH_LOC_UUID=$(scselect | tail -n +2 | grep -F "$SSID")

# If there is no matching location, select Automatic (might not exist)
if [ "${MATCH_LOC_UUID}" ]; then
  scselect $(<<< "${MATCH_LOC_UUID}" sed 's/^.*\([0-9A-F-]\{36\}\).*$/\1/')
else
  scselect Automatic
fi

# Write WiFi information into ~/.wifi_info
system_profiler SPNetworkDataType | \
sed -ne '/^    Wi-Fi/,/Service Order/p' \
> ~/.wifi_info
